name: Deploy to Production

on:
  # Temporarily disabled - enable after secrets are configured
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Run linter
        run: npm run lint
        continue-on-error: true

      - name: Build TypeScript
        run: npm run build

      - name: Run tests
        run: npm test
        continue-on-error: true

      - name: Deploy to Railway Production
        uses: bervProject/railway-deploy@main
        with:
          railway_token: ${{ secrets.RAILWAY_TOKEN }}
          service: teamnl-cloud9-production
        if: github.ref == 'refs/heads/main'

      - name: Wait for deployment
        run: sleep 30

      - name: Health check
        run: |
          curl -f https://teamnl-cloud9.up.railway.app/api/health || exit 1

      - name: Smoke tests
        run: |
          echo "Running smoke tests..."
          curl -f https://teamnl-cloud9.up.railway.app/api/workflow/status || exit 1

      - name: Notify success
        if: success()
        run: |
          echo "✅ Production deployment successful!"
          echo "🔗 URL: https://teamnl-cloud9.up.railway.app"

      - name: Notify failure
        if: failure()
        run: |
          echo "❌ Production deployment failed!"
          echo "Check logs and consider rollback"
