name: 🐛 Bug Report
description: Meld een bug in de TeamNL Cloud9 Dashboard
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees:
  - jeroendiepenbroek-lgtm

body:
  - type: markdown
    attributes:
      value: |
        Bedankt voor het melden van een bug! Dit helpt ons de applicatie te verbeteren.

  - type: textarea
    id: description
    attributes:
      label: 🐛 Bug Beschrijving
      description: Beschrijf de bug in detail
      placeholder: Vertel ons wat er fout gaat...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: 🔄 Stappen om te Reproduceren
      description: Stappen om de bug te reproduceren
      placeholder: |
        1. Ga naar '...'
        2. Klik op '...'
        3. Scroll naar '...'
        4. Zie fout
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: ✅ Verwacht Gedrag
      description: Wat had je verwacht dat er zou gebeuren?
      placeholder: Beschrijf het verwachte resultaat...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: ❌ Daadwerkelijk Gedrag
      description: Wat gebeurde er in plaats daarvan?
      placeholder: Beschrijf wat er echt gebeurde...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 📋 Logs/Screenshots
      description: Voeg relevante logs, error messages of screenshots toe
      placeholder: Plak logs of sleep screenshots hier...

  - type: dropdown
    id: component
    attributes:
      label: 🧩 Component
      description: Welk onderdeel van de applicatie is getroffen?
      options:
        - Frontend (HTML GUI)
        - Backend API
        - Database (Prisma)
        - Sync Service
        - CLI Tools
        - Documentation
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: 📦 Versie
      description: Welke versie gebruik je? (Check package.json)
      placeholder: v0.1.0

  - type: dropdown
    id: severity
    attributes:
      label: 🔥 Severity
      description: Hoe ernstig is deze bug?
      options:
        - Critical (app crashed/onbruikbaar)
        - High (belangrijke feature werkt niet)
        - Medium (feature werkt niet zoals verwacht)
        - Low (kleine issue, heeft workaround)
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 🖥️ Environment
      description: Informatie over je environment
      value: |
        - OS: [bijv. macOS, Windows, Linux]
        - Node version: [run `node -v`]
        - npm version: [run `npm -v`]
        - Database: [SQLite/PostgreSQL]
        - Browser: [indien relevant]

  - type: textarea
    id: additional
    attributes:
      label: ➕ Aanvullende Context
      description: Andere relevante informatie
      placeholder: Voeg context toe die kan helpen...

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Checklist
      options:
        - label: Ik heb gezocht naar vergelijkbare issues
          required: true
        - label: Ik heb de documentatie gecontroleerd
          required: true
        - label: Ik kan de bug consistent reproduceren
          required: false
