#!/bin/bash
# Run migration 010 on Supabase

echo "========================================="
echo "Migration 010: Update sync_logs table"
echo "========================================="
echo ""
echo "📋 Instructions:"
echo ""
echo "1. Open Supabase SQL Editor:"
echo "   https://supabase.com/dashboard/project/bktbeefdmrpxhsyyalvc/sql"
echo ""
echo "2. Copy/paste the migration file:"
echo "   supabase/migrations/010_update_sync_logs_for_auto_sync.sql"
echo ""
echo "3. Click 'Run' to execute"
echo ""
echo "4. Check the output for success messages"
echo ""
echo "========================================="
echo ""
echo "🔍 Preview of migration:"
cat supabase/migrations/010_update_sync_logs_for_auto_sync.sql | head -30
echo ""
echo "... (see full file for complete migration)"
echo ""
echo "========================================="
