#!/bin/bash

echo "🏗️  TeamNL Cloud9 - Development Workflow Setup"
echo "=============================================="
echo ""

# Check if on main branch
CURRENT_BRANCH=$(git branch --show-current)
if [ "$CURRENT_BRANCH" != "main" ]; then
    echo "⚠️  Niet op main branch. Checkout main eerst:"
    echo "   git checkout main"
    exit 1
fi

echo "📋 Step 1: Create develop branch"
echo "--------------------------------"
if git show-ref --verify --quiet refs/heads/develop; then
    echo "✅ develop branch bestaat al"
else
    echo "Creating develop branch..."
    git checkout -b develop
    git push -u origin develop
    echo "✅ develop branch aangemaakt en gepusht"
fi

echo ""
echo "📋 Step 2: Setup branch protection"
echo "-----------------------------------"
echo "⚠️  Handmatige actie vereist!"
echo ""
echo "Ga naar GitHub repository settings:"
echo "1. Settings → Branches → Add branch protection rule"
echo ""
echo "Voor 'main' branch:"
echo "  ✓ Require pull request before merging"
echo "  ✓ Require status checks (CI must pass)"
echo "  ✓ Require branches to be up to date"
echo ""
echo "Voor 'develop' branch:"
echo "  ✓ Require pull request before merging"
echo ""
read -p "Druk ENTER als branch protection is geconfigureerd..."

echo ""
echo "📋 Step 3: Railway environments setup"
echo "--------------------------------------"
echo ""
echo "⚠️  Railway dashboard actie vereist!"
echo ""
echo "1. Ga naar: https://railway.app"
echo "2. Open je project: TeamNL-Cloud9-Racing-Team"
echo "3. Klik 'Settings' → 'Environments'"
echo "4. Create new environment: 'staging'"
echo "5. Configure staging:"
echo "   - Branch: develop"
echo "   - Variables: (kopieer van .env.staging)"
echo "6. Add PostgreSQL database voor staging"
echo ""
read -p "Druk ENTER als Railway staging is geconfigureerd..."

echo ""
echo "📋 Step 4: GitHub Secrets setup"
echo "--------------------------------"
echo ""
echo "Ga naar: Settings → Secrets → Actions"
echo "Add secret: RAILWAY_TOKEN"
echo "Value: (krijg je van: railway login && railway whoami --token)"
echo ""
read -p "Druk ENTER als GitHub secrets zijn geconfigureerd..."

echo ""
echo "📋 Step 5: Test workflow"
echo "------------------------"
echo ""
echo "Test de complete workflow:"
echo ""
echo "# 1. Create feature branch"
echo "git checkout develop"
echo "git checkout -b feature/test-workflow"
echo ""
echo "# 2. Make a small change"
echo "echo '# Test' >> README.md"
echo "git add README.md"
echo "git commit -m 'test: workflow test'"
echo ""
echo "# 3. Push feature branch"
echo "git push origin feature/test-workflow"
echo ""
echo "# 4. Create PR naar develop op GitHub"
echo "# 5. Merge PR → Auto-deploy naar staging"
echo "# 6. Test staging: https://teamnl-staging.up.railway.app/api/health"
echo "# 7. Create PR van develop → main"
echo "# 8. Merge → Auto-deploy naar production"
echo ""

echo ""
echo "✅ Setup compleet!"
echo ""
echo "📚 Documentatie:"
echo "   - Workflow guide: docs/DEV-PROD-WORKFLOW.md"
echo "   - Deployment checklist: docs/DEPLOYMENT-CHECKLIST.md"
echo ""
echo "🚀 Next steps:"
echo "   1. Test de workflow met een kleine feature"
echo "   2. Verifieer staging environment"
echo "   3. Deploy naar production via develop → main"
echo ""
echo "💡 Tips:"
echo "   - Altijd via feature branches werken"
echo "   - Test lokaal voor pushen"
echo "   - Gebruik staging voor acceptance testing"
echo "   - Houd develop stabiel"
echo ""
echo "🎉 Happy coding!"
